canonical/sdcore-nrf-k8s-operator

- .github/workflows/publish-lib.yaml
Fixes bug in CI where charmcraft was not available to publish the lib
> Fixes bug in CI where charmcraft was not available to publish the lib

- lib/charms/sdcore_nrf/v0/fiveg_nrf.py
- requirements.txt
- test-requirements.txt
Fixes requirer docs and adds `pytest-interface-tester` as required dependency.
> Adds pytest-interaface-tester back to required deps

- lib/charms/sdcore_nrf/v0/fiveg_nrf.py
Fixes `charmcraft fetch-lib` command
> Fixing charmcraft fetch-lib command

- src/charm.py
- tests/unit/test_charm.py
Support for providing nrf url even when multiple requirers. Before applying this fix, the NRF use to produce this log when related to multiple charms:
```
Traceback (most recent call last):
File "/var/lib/juju/agents/unit-nrf-0/charm/./src/charm.py", line 227, in <module>
main(NRFOperatorCharm)
File "/var/lib/juju/agents/unit-nrf-0/charm/venv/ops/main.py", line 441, in main
_emit_charm_event(charm, dispatcher.event_name)
File "/var/lib/juju/agents/unit-nrf-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
event_to_emit.emit(*args, **kwargs)
File "/var/lib/juju/agents/unit-nrf-0/charm/venv/ops/framework.py", line 354, in emit
framework._emit(event)
File "/var/lib/juju/agents/unit-nrf-0/charm/venv/ops/framework.py", line 830, in _emit
self._reemit(event_path)
File …
```
> [Bug fix] Support for providing the NRF url to multiple requirers

- lib/charms/sdcore_nrf/v0/fiveg_nrf.py
- tests/unit/charms/sdcore_nrf/v0/test_fiveg_nrf_requirer_interface.py
Reduces log level for invalid relation data. The logs were filled with these types of logs when deploying sdcore:
```
unit-nssf-0: 10:19:07 ERROR unit.nssf/0.juju-log fiveg_nrf:6: Invalid data: 1 validation error for ProviderSchema
app -> url
field required (type=value_error.missing)
unit-nssf-0: 10:19:07 ERROR unit.nssf/0.juju-log fiveg_nrf:6: Invalid relation data: {}
```
When the relation is created, it's normal for the relation data not to be valid, those are not errors.
> [Bug fix] Reduces log level for invalid relation data

- README.md
- charmcraft.yaml
- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- metadata.yaml
- requirements.txt
- src/charm.py
- src/templates/nrfcfg.yaml.j2
- tests/integration/test_integration.py
- tests/unit/test_charm.py
Implements certificates interface and new certificate management. Here the workload will be set to use HTTPS for its SBI interface only when certificates are available (the relation to the TLS provider was created and certificates were provided).
Event management:
- On certificates relation created: Creates private key
- On certificates relation joined: Creates CSR based on private key and requests certificate
- On certificate available: Stores certificate and reconfigures the AMF workload to use HTTPS instead of HTTP
- On certificates relation broken: Deletes private key, CSR and Certificate and reconfigurs AMF workload to use HTTP instead of HTTPS
Notes:
- The path for certificates are hardcoded in the upstream code (ref [here](https://github.com/omec-project/nrf/blob/master/util/util.go …
> [Feat] Implements certificates interface

- README.md
- lib/charms/sdcore_nrf/v0/fiveg_nrf.py
- tests/unit/charms/sdcore_nrf/v0/dummy_requirer_charm/src/dummy_requirer_charm.py
- tests/unit/charms/sdcore_nrf/v0/test_fiveg_nrf_requirer_interface.py
- tox.ini
- Adds new, custom `nrf_broken` event to enable support for `relation-broken` in SD-Core charms
> Adding support for relation-broken event

- requirements.txt
Latest `ops` is incompatible with `scenario`. Due to this, integration and unit tests fail.
This PR pins `ops` version to the last compatible one, which is `2.4.1`
> (FIX) Downgrading ops to 2.4.1

- README.md
- src/charm.py
- tests/integration/test_integration.py
- tests/unit/expected_config/config.conf
- tests/unit/test_charm.py
Enforces TLS integration in the charm. Charm remains in blocked state until the `certificates` relation is created, and in waiting status until a certificate is stored.
> Enforce TLS Integration

- tests/integration/test_integration.py
Not waiting for all 3 units to settle could cause sporadic failures.
> Fix integration test -- wait for all 3 units to settle

- README.md
Removes the `--trust` flag. After replacing `KubernetesServicePatch` with `ops.set_ports` it's not needed anymore.
> chore: Removing --trust flag

- .github/workflows/main.yaml
- README.md
- lib/charms/sdcore_nrf_k8s/v0/fiveg_nrf.py
- metadata.yaml
- src/charm.py
- test-requirements.txt
- tests/unit/charms/sdcore_nrf/v0/dummy_provider_charm/src/dummy_provider_charm.py
- tests/unit/charms/sdcore_nrf/v0/dummy_requirer_charm/src/dummy_requirer_charm.py
- tests/unit/charms/sdcore_nrf/v0/test_fiveg_nrf_requirer_interface.py
- tests/unit/test_charm.py
- tox.ini
Add -k8s as a suffix in both github and Charmhub name to follow [TE042](https://docs.google.com/document/d/1R0UzoPr3vvorhbBJYBz-5gZkTCTL2a9_R6xV8K4_i-8/edit) . 
- Create new fiveg_nrf library
- Pin macaroonbakery to 1.3.2 which installed by juju client indirectly through pytest_operator.
- The next protobuf version 4.21.0 has the breaking changes with the existing code
- https://protobuf.dev/news/2022-05-06/#python-updates
> chore: Rename SD-Core charms by adding -k8s as a suffix

- src/charm.py
- tests/unit/test_charm.py
Removes explicit certificate relations and defer events
I have made corresponding changes to the documentation
Any dependent changes have been merged and published in downstream modules
I have bumped the version of the library
> feat: Remove defer

- .github/workflows/main.yaml
The dependabot Pull Requests currently fail because we use `inherit` for passing the secret to check-libraries instead of passing it directly. PR #81 covered this partially but we were missing it in 1 place.
> fix: specify secret in check-library workflow

- lib/charms/loki_k8s/v1/loki_push_api.py
- metadata.yaml
- requirements.in
- requirements.txt
- src/charm.py
- tests/integration/test_integration.py
Implement log forwarding via Pebble's new log-target spec. We use the loki_push_api charm relation to get the loki endpoint.
> feat: implement log forwarding

- src/charm.py
- tests/unit/test_charm.py
The `collect_unit_status` event is triggered after every hook. It will be triggered after db relation broken event. So we can remove the handler.
> chore: use collect status event to set blocked status on relation broken

- lib/charms/sdcore_nrf_k8s/v0/fiveg_nrf.py
- pyproject.toml
- src/charm.py
- test-requirements.in
- test-requirements.txt
- tests/unit/test_charm.py
- tox.ini
Move to ruff and codespell for linting. `pyproject-flake8` is currently broken on Python 3.12, making development on Noble break.
> chore: Move to codespell and ruff

- src/charm.py
- tests/unit/expected_config/config.conf
- tests/unit/test_charm.py
This changes the configuration of the NRF to use the application name, as it will match the k8s service name, instead of the pod IP. This is also done in the deployment helm charts upstream.
Using the pod IP is problematic in a dynamic environment like k8s. This causes issue in many services if the NRF restarts and changes IPs. Because the NRF is the discovery service for the other NFs, it needs to always be reachable.
> fix: Use service name instead of IP in URL

- .github/workflows/dependabot_pr.yaml
- .github/workflows/issues.yaml
- .github/workflows/main.yaml
- .github/workflows/promote.yaml
Use the release version of sdcore-github workflows instead of using the main branch.
This will allow to make breaking changes in the workflows without breaking its dependents. More specifically, we are working on building the charm in its independent workflow step instead of having it built in the integration tests. Making such change in the workflows would break every NF CI until they adapt to the new workflow approach. Here we want to avoid this and have the workflow keep on working until we intentionally adopt the new approach.
> chore: use release version of sdcore github workflows

- tests/unit/charms/sdcore_nrf/v0/test_fiveg_nrf_provider_interface.py
- tests/unit/charms/sdcore_nrf/v0/test_fiveg_nrf_requirer_interface.py
- tests/unit/test_charm.py
Remove `unittest` and use only `pytest` framework to run the unit tests.
There are no modifications in the core content of the tests.
https://juju.is/docs/sdk/write-a-unit-test-for-a-charm
Actions on this PR:
- Add a `@pytest.fixture` configure harness
- Add a `@pytest.fixture` setup patches and mock harness
- Continue using `Mock`, `call` and `patch` from the `unittest.Mock` library
- Use `assert` instead of `self.assert...` methods
> chore: Use Pytest for UTs

- .github/workflows/main.yaml
bump sdcore-github-workflows to 0.0.2  to fix the publishing issue which was not related to publishing the charm to the dev branch.
> chore: bump sdcore-github-workflows to 0.0.2

- test-requirements.in
- test-requirements.txt
- tests/unit/charms/sdcore_nrf/v0/test_fiveg_nrf_provider_interface.py
- tests/unit/charms/sdcore_nrf/v0/test_fiveg_nrf_requirer_interface.py
- tests/unit/fixtures.py
- tests/unit/test_charm_certificate_relation_broken.py
- tests/unit/test_charm_collect_status.py
- tests/unit/test_charm_configure.py
- tests/unit/test_charm_fiveg_nrf_relation_joined.py
Now that scenario testing is built into ops we don't need to import it as a separate dependency. Here we use ops.testing instead of scenario. Both have the same API.
> chore: use built-in testing from ops

- src/prometheus_alert_rules/nrf_down.rule
This PR aims to add the alert rule for NRF availability. The alert will be fired when NRF remains down for at least 5 minutes.
> feat: add alert rule for NRF availability

- CONTRIBUTING.md
- README.md
Use Juju 3.5 and Microk8s 1.31-strict/stable in the docs
> chore: use Juju 3.5 and Microk8s 1.31-strict/stable in the docs

- tests/integration/test_integration.py
This PR sets the the `6/stable` channel for mongodb charm instead of `6/beta`
https://github.com/canonical/mongodb-k8s-operator/issues/218 seems fixed in `6/stable` so the tests can be restored
> chore: move to channel 6/stable in mongodb

- .github/workflows/main.yaml
- .github/workflows/promote.yaml
- README.md
- terraform/variables.tf
Bumps project version to `1.6` after creation of `v1.5` release branch
NOTE:
Due to a cyclic dependency between the AMF, NMS and NRF, integration tests still use NMS from `1.5/edge`.
> chore: Bumps project version to 1.6

- .github/renovate.json5
- .github/workflows/1_5_scheduled_runs.yaml
- Configures renovate to cover `v1.5`
- Adds `v1.5` scheduled CI runs
> chore: Configures renovate to cover v1.5; adds v1.5 scheduled CI runs

- README.md
- charmcraft.yaml
Bump the underlying workload to the latest upstream release: v1.6.2
- https://github.com/omec-project/nrf/releases/tag/v1.6.2
> chore: bump nrf rock to v1.6.2

- .github/workflows/1_5_scheduled_runs.yaml
- .github/workflows/dependabot_pr.yaml
- .github/workflows/issues.yaml
- .github/workflows/main.yaml
- .github/workflows/promote.yaml
- .github/workflows/tics.yaml
- .github/workflows/update-libs.yaml
- tox.ini
Adds a TiCS static analysis workflow to run every week, which is the maximum frequency recommend.
The manual trigger option allows developers to manually trigger the analysis workflow whenever needed.
Besides, this PR adds coverage.xml as an outcome of unit tests as this file is required for TiCS static analysis.
> feat: add TICS analysis workflow

- tests/integration/test_integration.py
This PR removes a workaround and specifies the base instead of series for charms that support 2 bases.
> chore: use base instead of series in charm deployment in integration tests

- src/templates/nrfcfg.yaml.j2
- tests/unit/expected_config/config.conf
MongoDB information is duplicated in the configuration file. Turns out that in the NRF, the parameters are called `MongoDBName` and `MongoDBUrl`. We can remove the `mongodb` field and it's nested strutcs.
See the upstream code https://github.com/omec-project/nrf/blob/main/factory/config.go#L46
> chore: remove unused config file params

- tests/integration/test_integration.py
Grafana agent charm has been release to `1/stable`. This PR updates it in the integration tests
> fix: set grafana agent channel to 1/stable in integration tests
